FROM python:3.13-alpine AS base

ARG FOLDER=/app

WORKDIR ${FOLDER}

RUN apk add --no-cache shadow

RUN groupadd -g 1000 devgroup && \
    useradd -u 1000 -g 1000 -m devuser

COPY . /app

RUN chown -R devuser:devgroup /app

RUN pip install -r requirements.txt --no-cache-dir

USER devuser

EXPOSE 8000

CMD ["fastapi", "run", "src/main.py", "--proxy-headers", "--port", "8000", "--reload"]
