services:
  python_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: python_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - IDENTIFIER=component-fastapi-beta
    restart: "no"