apiVersion: apps/v1
{{- if eq .Values.stage "development"}}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  {{- if eq .Values.stage "development"}}
  serviceName: app
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: diploi-pull-secret
      {{- if eq .Values.stage "development"}}
      initContainers:
        - name: install-dependencies
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
          - |
            uv sync --locked && \
            mkdir -p /etc/supervisor/conf.d && \
            cp /app/{{ .Values.identifier }}/supervisord.conf /etc/supervisord.conf 2>/dev/null || : && \
            cp /app/{{ .Values.identifier }}/fastapi-supervisor.conf /etc/supervisor/conf.d/fastapi-supervisor.conf 2>/dev/null || :
          workingDir: /app/{{ .Values.identifier }}
          volumeMounts:
            - name: app-mount
              mountPath: /app
            - name: supervisor-config
              mountPath: /etc/supervisor
      {{- end }}
      containers:
        - name: app
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: IDENTIFIER
              value: {{ .Values.identifier | quote }}
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- if hasKey .Values.storage "code" }}
            - name: app-mount
              mountPath: /app
            {{- end }}
            - name: supervisor-config
              mountPath: /etc/supervisor
      volumes:
        {{- if hasKey .Values.storage "code" }}
        - name: app-mount
          hostPath:
            path: {{ .Values.storage.code.hostPath }}
        {{- end }}
        - name: supervisor-config
          emptyDir: {}
